### ISSUE TITLE
We're broken on master (929161943f19)

### ISSUE THREAD

**Issue by aspiwack** [tweag/linear-base#452] opened 2023-05-04 14:49 UTC
Linear-base appears to trigger an assertion failure in GHC master (annoyingly as I was trying to test stuff). It's not our fault, but we need to report, and I won't have time to reduce the bug today. So writing down what I observed.

```
[82 of 89] Compiling Data.HashMap.Mutable.Linear.Internal ( src/Data/HashMap/Mutable/Linear/Internal.hs, /home/aspiwack/projects/tweag/linear-base/master/dist-newstyle/build/x86_64-linux/ghc-9.7.20230207/linear-base-0.3.1/build/Data/HashMap/Mutable/Linear/Internal.o )
WARNING:
  Simplifier bailing out
  Data.HashMap.Mutable.Linear.Internal, after 4 iterations [575, 34, 12, 11]
    Size = {terms: 3,349, types: 4,600, coercions: 944, joins: 4/37}
  Call stack:
      CallStack (from HasCallStack):
        warnPprTrace, called at compiler/GHC/Core/Opt/Simplify.hs:195:9 in ghc:GHC.Core.Opt.Simplify

<no location info>: error:
    panic! (the 'impossible' happened)
  GHC version 9.7.20230207:
	ASSERT failed!
  Coercion = Sym co_iPMZ
  LHS ty = RobinArr k_s1n6j v_s1n6k
  RHS ty = RobinArr k_s1n6j v'_s1n6l
  cs = Tc(0)
  coercion role = nominal
  Call stack:
      CallStack (from HasCallStack):
        assertPpr, called at compiler/GHC/Core/Coercion.hs:1126:5 in ghc:GHC.Core.Coercion
        mkSelCo_maybe, called at compiler/GHC/Core/Coercion.hs:1118:16 in ghc:GHC.Core.Coercion
        mkSelCo, called at compiler/GHC/Core/TyCo/Subst.hs:903:32 in ghc:GHC.Core.TyCo.Subst
  CallStack (from HasCallStack):
    panic, called at compiler/GHC/Utils/Error.hs:454:29 in ghc:GHC.Utils.Error


Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

**Comment by aspiwack** [comment] 2023-05-05 13:27
I used a slightly more recent master (e8b72ff6e4aee1f889a9168df57bb1b00168fd21) today (a bunch of commits landed this morning, and it helped me make sure that there was no confusion with my experiments from yesterday).

I managed to reduce the file quite a bit (see below). But it still had a dependency on `Data.Mutable.Array.Linear` that is surprisingly hard to shake. And would make it difficult to analyse.

The code is pretty much meaningful at this stage, but what's going on is that we're implementing `map` in place on the Hashmap. To do that we need to `unsafeCoerce` (in the whole code it's used twice: we coerce new items to the old type as we're adding them in, then we coerce the whole hashmap to the new type, only the latter is left in the reduced version).

Of course, we're living dangerously, using `unsafeCoerce`, but there's still a bug in the compiler that needs investigating. This is not reduced enough to submit a bug report today, I don't think but I need to move on for the rest of the afternoon.

---

```haskell
{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE LinearTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE UnliftedNewtypes #-}
{-# LANGUAGE EmptyCase #-}

module Data.HashMap.Mutable.Linear.Internal (mapMaybeWithKey, shiftSegmentBackward) where

import Data.Array.Mutable.Linear (Array)
import qualified Data.Array.Mutable.Linear as Array
import Data.Unrestricted.Linear
import Unsafe.Coerce (UnsafeEquality (..), unsafeEqualityProof)


-- | A mutable hashmap with a linear interface.
data HashMap k v where
  -- |
  -- @loadFactor m = size m / cap m@
  --
  -- Invariants:
  -- - array is non-empty
  -- - (count / capacity) <= constMaxLoadFactor.
  HashMap ::
    -- | Underlying array.
    !(RobinArr k v) %1 ->
    HashMap k v

-- | An array of Robin values
--
-- Each cell is Nothing if empty and is a RobinVal with the correct
-- PSL otherwise.
type RobinArr k v = Array (Maybe (RobinVal k v))

-- | Robin values are triples of the key, value and PSL
-- (the probe sequence length).
data RobinVal k v

-- # Construction and Modification
--------------------------------------------------

array_read :: Array a %1 -> (Ur a, Array a)
array_read arr = Array.unsafeRead arr 0
{-# NOINLINE array_read #-}

unsafe_coerce :: forall a b. a %1 -> b
unsafe_coerce a =
  case unsafeEqualityProof @a @b of
    UnsafeRefl -> a

-- | Same as 'mapMaybe', but also has access to the keys.
mapMaybeWithKey ::
  forall k v v'.
  (Eq k) =>
  HashMap k v %1 ->
  HashMap k v'
mapMaybeWithKey (HashMap arr) =
    case mapAndPushBack 0 arr of
      (Ur c, arr2) -> HashMap (unsafe_coerce arr2)
  where
    -- Going from arr[0] to arr[size-1] map each element while
    -- simultaneously pushing elements back if some earlier element(s)
    -- were deleted in a contiguous segment and if the current
    -- element has PSL > 0. Maintain a counter of how
    -- far to push elements back. At arr[size-1] if needed, call
    -- shiftSegmentBackward with the counter at arr[0].
    mapAndPushBack ::
      Int -> -- Current index
      RobinArr k v %1 ->
      (Ur Int, RobinArr k v) -- The new count and fully mapped array
    mapAndPushBack end arr
      | (0 > end) =
          (Ur 0, shiftSegmentBackward end arr)
      | otherwise =
          mapAndPushBack end arr



-- | Shift all cells with PSLs > 0 in a continuous segment
-- following the deleted cell, backwards by one and decrement
-- their PSLs.
shiftSegmentBackward ::
  (Eq k) =>
  Int ->
  RobinArr k v %1 ->
  RobinArr k v
shiftSegmentBackward s arr =
  case array_read arr of
    (Ur Nothing, arr') -> arr'
    (Ur (Just _), arr') -> shiftSegmentBackward s (case undefined of {})
```

**Comment by aspiwack** [comment] 2023-05-05 13:30
Also removing the _completely unused_ `Eq` constraint (it can be anything, it just needs to be a constraint over `k`, as far I as can tell) makes the bug disappear.

I did check, by the way, that the bug only occurs with at least `-O` (I didn't check with `-O2`, though).

**Comment by aspiwack** [comment] 2023-05-09 09:18
Thanks @monoidal your minimisation skills are as impressive are ever.

**Comment by monoidal** [comment] 2023-05-11 12:56
I've prepared a fix https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10424 and confirmed that it fixes  `linear-base`.

**Comment by monoidal** [comment] 2023-05-15 11:53
The fix landed in master and I've marked it for backporting to 9.6.2.

We could optionally add a conditional `-fno-opt-coercion` as a workaround, but in released versions the assertions are off, and in master the bug is patched. Lint fails anyways because of GHC bugs https://gitlab.haskell.org/ghc/ghc/-/issues/23370 and https://gitlab.haskell.org/ghc/ghc/-/issues/23380. So I don't think there's much gain from that, closing.

**Closed by monoidal** 2023-05-15 11:53 UTC
Labels: type: bug
